/* global Harmony StateScene */

const LoadScene = new Harmony.Scene({
  create: async (engine) => {
    document.querySelector('#loading').classList.remove('hidden')

    await engine.render.loadImage({ name: 'question', url: './assets/images/question.png' })
    await engine.render.loadImage({ name: 'a', url: './assets/images/alphabet/a.jpg' })
    await engine.render.loadImage({ name: 'b', url: './assets/images/alphabet/b.jpg' })
    await engine.render.loadImage({ name: 'c', url: './assets/images/alphabet/c.jpg' })
    await engine.render.loadImage({ name: 'd', url: './assets/images/alphabet/d.jpg' })
    await engine.render.loadImage({ name: 'e', url: './assets/images/alphabet/e.jpg' })
    await engine.render.loadImage({ name: 'f', url: './assets/images/alphabet/f.jpg' })
    await engine.render.loadImage({ name: 'g', url: './assets/images/alphabet/g.jpg' })
    await engine.render.loadImage({ name: 'h', url: './assets/images/alphabet/h.jpg' })
    await engine.render.loadImage({ name: 'i', url: './assets/images/alphabet/i.jpg' })
    await engine.render.loadImage({ name: 'j', url: './assets/images/alphabet/j.jpg' })
    await engine.render.loadImage({ name: 'k', url: './assets/images/alphabet/k.jpg' })
    await engine.render.loadImage({ name: 'l', url: './assets/images/alphabet/l.jpg' })
    await engine.render.loadImage({ name: 'm', url: './assets/images/alphabet/m.jpg' })
    await engine.render.loadImage({ name: 'n', url: './assets/images/alphabet/n.jpg' })
    await engine.render.loadImage({ name: 'o', url: './assets/images/alphabet/o.jpg' })
    await engine.render.loadImage({ name: 'p', url: './assets/images/alphabet/p.jpg' })
    await engine.render.loadImage({ name: 'q', url: './assets/images/alphabet/q.jpg' })
    await engine.render.loadImage({ name: 'r', url: './assets/images/alphabet/r.jpg' })
    await engine.render.loadImage({ name: 's', url: './assets/images/alphabet/s.jpg' })
    await engine.render.loadImage({ name: 't', url: './assets/images/alphabet/t.jpg' })
    await engine.render.loadImage({ name: 'u', url: './assets/images/alphabet/u.jpg' })
    await engine.render.loadImage({ name: 'v', url: './assets/images/alphabet/v.jpg' })
    await engine.render.loadImage({ name: 'w', url: './assets/images/alphabet/w.jpg' })
    await engine.render.loadImage({ name: 'x', url: './assets/images/alphabet/x.jpg' })
    await engine.render.loadImage({ name: 'y', url: './assets/images/alphabet/y.jpg' })
    await engine.render.loadImage({ name: 'z', url: './assets/images/alphabet/z.jpg' })
    await engine.render.loadImage({ name: 'arancia', url: './assets/images/things/arancia.jpg' })
    await engine.render.loadImage({ name: 'brucco', url: './assets/images/things/brucco.jpg' })
    await engine.render.loadImage({ name: 'cane', url: './assets/images/things/cane.jpg' })
    await engine.render.loadImage({ name: 'delfino', url: './assets/images/things/delfino.jpg' })
    await engine.render.loadImage({ name: 'elefante', url: './assets/images/things/elefante.jpg' })
    await engine.render.loadImage({ name: 'fiore', url: './assets/images/things/fiore.jpg' })
    await engine.render.loadImage({ name: 'gufo', url: './assets/images/things/gufo.jpg' })
    await engine.render.loadImage({ name: 'hotel', url: './assets/images/things/hotel.jpg' })
    await engine.render.loadImage({ name: 'isola', url: './assets/images/things/isola.jpg' })
    await engine.render.loadImage({ name: 'jeep', url: './assets/images/things/jeep.jpg' })
    await engine.render.loadImage({ name: 'koala', url: './assets/images/things/koala.jpg' })
    await engine.render.loadImage({ name: 'leone', url: './assets/images/things/leone.jpg' })
    await engine.render.loadImage({ name: 'maiale', url: './assets/images/things/maiale.jpg' })
    await engine.render.loadImage({ name: 'nave', url: './assets/images/things/nave.jpg' })
    await engine.render.loadImage({ name: 'orso', url: './assets/images/things/orso.jpg' })
    await engine.render.loadImage({ name: 'polpo', url: './assets/images/things/polpo.jpg' })
    await engine.render.loadImage({ name: 'quaderno', url: './assets/images/things/quaderno.jpg' })
    await engine.render.loadImage({ name: 'riccio', url: './assets/images/things/riccio.jpg' })
    await engine.render.loadImage({ name: 'serpente', url: './assets/images/things/serpente.jpg' })
    await engine.render.loadImage({ name: 'torre', url: './assets/images/things/torre.jpg' })
    await engine.render.loadImage({ name: 'uccello', url: './assets/images/things/uccello.jpg' })
    await engine.render.loadImage({ name: 'violino', url: './assets/images/things/violino.jpg' })
    await engine.render.loadImage({ name: 'waffle', url: './assets/images/things/waffle.jpg' })
    await engine.render.loadImage({ name: 'xilofono', url: './assets/images/things/xilofono.jpg' })
    await engine.render.loadImage({ name: 'yoghurt', url: './assets/images/things/yoghurt.jpg' })
    await engine.render.loadImage({ name: 'zebra', url: './assets/images/things/zebra.jpg' })

    await engine.audio.loadClip({ name: 'correct', url: './assets/audio/correct.wav' })
    await engine.audio.loadClip({ name: 'win', url: './assets/audio/win.wav' })
    await engine.audio.loadClip({ name: 'a', url: './assets/audio/alphabet/a.mp3' })
    await engine.audio.loadClip({ name: 'b', url: './assets/audio/alphabet/b.mp3' })
    await engine.audio.loadClip({ name: 'c', url: './assets/audio/alphabet/c.mp3' })
    await engine.audio.loadClip({ name: 'd', url: './assets/audio/alphabet/d.mp3' })
    await engine.audio.loadClip({ name: 'e', url: './assets/audio/alphabet/e.mp3' })
    await engine.audio.loadClip({ name: 'f', url: './assets/audio/alphabet/f.mp3' })
    await engine.audio.loadClip({ name: 'g', url: './assets/audio/alphabet/g.mp3' })
    await engine.audio.loadClip({ name: 'h', url: './assets/audio/alphabet/h.mp3' })
    await engine.audio.loadClip({ name: 'i', url: './assets/audio/alphabet/i.mp3' })
    await engine.audio.loadClip({ name: 'j', url: './assets/audio/alphabet/j.mp3' })
    await engine.audio.loadClip({ name: 'k', url: './assets/audio/alphabet/k.mp3' })
    await engine.audio.loadClip({ name: 'l', url: './assets/audio/alphabet/l.mp3' })
    await engine.audio.loadClip({ name: 'm', url: './assets/audio/alphabet/m.mp3' })
    await engine.audio.loadClip({ name: 'n', url: './assets/audio/alphabet/n.mp3' })
    await engine.audio.loadClip({ name: 'o', url: './assets/audio/alphabet/o.mp3' })
    await engine.audio.loadClip({ name: 'p', url: './assets/audio/alphabet/p.mp3' })
    await engine.audio.loadClip({ name: 'q', url: './assets/audio/alphabet/q.mp3' })
    await engine.audio.loadClip({ name: 'r', url: './assets/audio/alphabet/r.mp3' })
    await engine.audio.loadClip({ name: 's', url: './assets/audio/alphabet/s.mp3' })
    await engine.audio.loadClip({ name: 't', url: './assets/audio/alphabet/t.mp3' })
    await engine.audio.loadClip({ name: 'u', url: './assets/audio/alphabet/u.mp3' })
    await engine.audio.loadClip({ name: 'v', url: './assets/audio/alphabet/v.mp3' })
    await engine.audio.loadClip({ name: 'w', url: './assets/audio/alphabet/w.mp3' })
    await engine.audio.loadClip({ name: 'x', url: './assets/audio/alphabet/x.mp3' })
    await engine.audio.loadClip({ name: 'y', url: './assets/audio/alphabet/y.mp3' })
    await engine.audio.loadClip({ name: 'z', url: './assets/audio/alphabet/z.mp3' })
    await engine.audio.loadClip({ name: 'arancia', url: './assets/audio/things/arancia.mp3' })
    await engine.audio.loadClip({ name: 'brucco', url: './assets/audio/things/brucco.mp3' })
    await engine.audio.loadClip({ name: 'cane', url: './assets/audio/things/cane.mp3' })
    await engine.audio.loadClip({ name: 'delfino', url: './assets/audio/things/delfino.mp3' })
    await engine.audio.loadClip({ name: 'elefante', url: './assets/audio/things/elefante.mp3' })
    await engine.audio.loadClip({ name: 'fiore', url: './assets/audio/things/fiore.mp3' })
    await engine.audio.loadClip({ name: 'gufo', url: './assets/audio/things/gufo.mp3' })
    await engine.audio.loadClip({ name: 'hotel', url: './assets/audio/things/hotel.mp3' })
    await engine.audio.loadClip({ name: 'isola', url: './assets/audio/things/isola.mp3' })
    await engine.audio.loadClip({ name: 'jeep', url: './assets/audio/things/jeep.mp3' })
    await engine.audio.loadClip({ name: 'koala', url: './assets/audio/things/koala.mp3' })
    await engine.audio.loadClip({ name: 'leone', url: './assets/audio/things/leone.mp3' })
    await engine.audio.loadClip({ name: 'maiale', url: './assets/audio/things/maiale.mp3' })
    await engine.audio.loadClip({ name: 'nave', url: './assets/audio/things/nave.mp3' })
    await engine.audio.loadClip({ name: 'orso', url: './assets/audio/things/orso.mp3' })
    await engine.audio.loadClip({ name: 'polpo', url: './assets/audio/things/polpo.mp3' })
    await engine.audio.loadClip({ name: 'quaderno', url: './assets/audio/things/quaderno.mp3' })
    await engine.audio.loadClip({ name: 'riccio', url: './assets/audio/things/riccio.mp3' })
    await engine.audio.loadClip({ name: 'serpente', url: './assets/audio/things/serpente.mp3' })
    await engine.audio.loadClip({ name: 'torre', url: './assets/audio/things/torre.mp3' })
    await engine.audio.loadClip({ name: 'uccello', url: './assets/audio/things/uccello.mp3' })
    await engine.audio.loadClip({ name: 'violino', url: './assets/audio/things/violino.mp3' })
    await engine.audio.loadClip({ name: 'waffle', url: './assets/audio/things/waffle.mp3' })
    await engine.audio.loadClip({ name: 'xilofono', url: './assets/audio/things/xilofono.mp3' })
    await engine.audio.loadClip({ name: 'yoghurt', url: './assets/audio/things/yoghurt.mp3' })
    await engine.audio.loadClip({ name: 'zebra', url: './assets/audio/things/zebra.mp3' })

    document.querySelector('#loading').classList.add('hidden')
  },
  update: (engine) => {
    engine.scene.switch(MemoryScene)
  }
})
